---
# Add Ansible Galaxy Packages here, role_example_hello included to prevent errors in template testing
- irixjp.role_example_hello           # https://galaxy.ansible.com/irixjp/role_example_hello
- grzegorznowak.nvm_node              # https://galaxy.ansible.com/grzegorznowak/nvm_node
- andrewrothstein.pandoc              # https://galaxy.ansible.com/andrewrothstein/pandoc
- staticdev.firefox                   # https://galaxy.ansible.com/staticdev/firefox
- don_rumata.ansible_role_install_wine  # https://galaxy.ansible.com/don_rumata/ansible_role_install_wine
#- geerlingguy.pip                     # https://galaxy.ansible.com/geerlingguy/pip
- gantsign.visual-studio-code         # https://galaxy.ansible.com/gantsign/visual-studio-code
...
