# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'devResources/**'
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'devResources/**'
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag

      - name: Login to GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_AUTH_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v4.0.0
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: ./Dockerfile
          
      - name: Push image
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile    
